# PyTorch

1. PyTorch是一个开源的Python机器学习库，基于Torch
2. 2017年1月，由Facebook人工智能研究院（FAIR）基于Torch推出了PyTorch。
3. PyTorch既可以看作加入了GPU支持的numpy，同时也可以看成一个拥有自动求导功能的强大的深度神经网络。

#### Tensors(张量)

1. Tensors 类似于 NumPy 的 ndarrays 
2. Tensors 可以使用 GPU 进行计算

In [4]:
import torch
import numpy as np

In [ ]:
x = torch.tensor([5.5, 3,4.5])
print(x)

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.0194e-38, 9.1837e-39, 4.6837e-39],
        [9.9184e-39, 9.0000e-39, 1.0561e-38],
        [1.0653e-38, 4.1327e-39, 8.9082e-39],
        [9.8265e-39, 9.4592e-39, 1.0561e-38],
        [1.0653e-38, 1.0469e-38, 9.5510e-39]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1590, 0.3415, 0.8028],
        [0.9350, 0.5723, 0.2788],
        [0.8585, 0.6793, 0.5615],
        [0.5624, 0.6208, 0.8827],
        [0.3424, 0.7919, 0.8383]])


In [4]:
x = torch.randn(5, 3)
print(x)

tensor([[-0.8659, -0.1031,  1.4662],
        [-1.6050,  0.9235, -0.1446],
        [ 1.5106,  1.0902, -1.1567],
        [ 1.5199,  1.2600, -0.9743],
        [-0.0088,  0.0428,  0.4185]])


##### rand 与randn
1. torch.rand()均匀分布：返回一个张量，包含了从区间[0, 1)的均匀分布中抽取的一组随机数。

2. torch.randn()标准正态分布：返回一个张量，包含了从标准正态分布（均值为0，方差为1，即高斯白噪声）中抽取的一组随机数。

In [9]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [11]:
x = x.new_ones(5, 3)      
# new_* methods take in sizes
print(x)

x = torch.randn_like(x)    
# override dtype!
print(x)                                      
# result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[-0.7041, -0.7569, -0.2750],
        [-0.5326, -1.1885,  0.2100],
        [-1.2384,  0.3443,  1.9162],
        [ 0.2743, -0.5969, -1.0648],
        [-0.8921, -0.2111, -0.3761]])


new_ones()
1. 返回一个与size大小相同的用1填充的张量。
2. 默认情况下，返回的Tensor具有与此张量相同的torch.dtype和torch.device。

加法操作

In [12]:
y = torch.rand(5, 3) #方式 1
print(x + y)

tensor([[ 0.1348, -0.3846,  0.1106],
        [ 0.2997, -0.4207,  1.0678],
        [-0.5004,  1.0730,  2.0611],
        [ 1.1052,  0.1043, -0.0917],
        [-0.6089,  0.7064,  0.2649]])


In [13]:
print(torch.add(x, y)) #方式 2

tensor([[ 0.1348, -0.3846,  0.1106],
        [ 0.2997, -0.4207,  1.0678],
        [-0.5004,  1.0730,  2.0611],
        [ 1.1052,  0.1043, -0.0917],
        [-0.6089,  0.7064,  0.2649]])


In [14]:
result = torch.empty(5, 3)
torch.add(x, y, out=result) # 提供一个输出 tensor 作为参数
print(result)

tensor([[ 0.1348, -0.3846,  0.1106],
        [ 0.2997, -0.4207,  1.0678],
        [-0.5004,  1.0730,  2.0611],
        [ 1.1052,  0.1043, -0.0917],
        [-0.6089,  0.7064,  0.2649]])


In [15]:
y.add_(x)  # in-place
print(y)

tensor([[ 0.1348, -0.3846,  0.1106],
        [ 0.2997, -0.4207,  1.0678],
        [-0.5004,  1.0730,  2.0611],
        [ 1.1052,  0.1043, -0.0917],
        [-0.6089,  0.7064,  0.2649]])


torch.view 改变一个 tensor 的大小或者形状

In [16]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [7]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

#### Attributes of a Tensor
Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [9]:
tensor = torch.rand(3,4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [12]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [14]:
tensor = torch.rand(4, 4)
print(tensor)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

tensor([[0.4567, 0.4524, 0.8394, 0.7076],
        [0.6096, 0.1368, 0.2035, 0.9238],
        [0.2937, 0.0267, 0.3833, 0.9110],
        [0.8282, 0.6367, 0.1356, 0.6972]])
First row: tensor([0.4567, 0.4524, 0.8394, 0.7076])
First column: tensor([0.4567, 0.6096, 0.2937, 0.8282])
Last column: tensor([0.7076, 0.9238, 0.9110, 0.6972])
Last column: tensor([0.7076, 0.9238, 0.9110, 0.6972])
tensor([[0.4567, 0.0000, 0.8394, 0.7076],
        [0.6096, 0.0000, 0.2035, 0.9238],
        [0.2937, 0.0000, 0.3833, 0.9110],
        [0.8282, 0.0000, 0.1356, 0.6972]])


#### PyTorch自动微分

+ 如果将torch.Tensor属性 requires_grad ，表明这个tensor是否是可求导的；设置为 True，则会开始跟踪针对 tensor 的所有操作,默认为False.
+ 要停止 tensor 历史记录的跟踪，您可以调用 .detach()，它将其与计算历史记录分离，并防止将来的计算被跟踪。


In [59]:
x=torch.tensor([2.0,2.0,3],requires_grad=True)

In [112]:
x = torch.ones(2, 3, requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [113]:
y = x + 2
print(y)

tensor([[3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>)


In [62]:
print(y.grad_fn)

In [114]:
z = y * y * 3
print(z)

tensor([[27., 27., 27.],
        [27., 27., 27.]], grad_fn=<MulBackward0>)


In [44]:
out = z.mean()
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [45]:
out.backward()

In [46]:
print(x.grad) # 梯度 d(out)/dx

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [15]:
a=torch.tensor([1.,2,3],requires_grad=True)
b=a**2
g=torch.tensor([1.0,0.2,0.01])
b.backward(g)
a.grad

tensor([2.0000, 0.8000, 0.0600])

不同的分量有不同的权重，例如三个loss，loss1，loss2，loss3，它们的权重可能是不一样的，可通过它来设置，即
dy/dx=0.1*dy1/dx+0.2*dy2/dx+0.01*dy3/dx